name: HideAndSeek
author: hctel
version: a0.1
main: be.hctel.renaissance.hideandseek.Hide
softdepend: ['Multiverse-Core', 'LibsDisguises', 'ViaVersion']
commands: 
  stats:
    usage: /stats [player]
    permission: hide.stats
    description: Check the stats of a player
  setrank:
    usage: /setrank <0-9>
    permission: hide.setrank
    description: Disguise your rank as another rank
  togglerank:
    usage: /togglerank
    permission: hide.setrank
    description: Toggles your rank visibility
  updateprofile:
    usage: /updateprofile <player> <category> <value>
    permission: hide.staff
    description: update a player's stats
  vote:
    usage: /vote <#>
    permission: hide.vote
    description: Vote for a map
  v:
    usage: /v <#>
    permission: hive.vote
    description: Vote for a map
  gotoworld:
    usage: /gotoworld <worldname>
    permission: hide.staff
    description: Go to a world
  taunt:
    usage: /taunt <taunt type>
    permission: hide.taunt
    description: Taunt!
  s:
    usage: /s
    permission: hide.admin
    description: Stops the server and sends everyone to the lobby