name: HideAndSeek
author: hctel
version: 1.0
api-version: 1.21.10
main: be.hctel.renaissance.hideandseek.Hide
depend: ['Multiverse-Core', 'ProtocolLib', 'packetevents']
load: POSTWORLD
commands: 
  vote:
    usage: /vote <#>
    permission: hide.default
    description: Vote for a map
  v:
    usage: /v <#>
    permission: hide.default
    description: Vote for a map
  gotoworld:
    usage: /gotoworld <worldname>
    permission: hide.staff
    description: Go to a world
  taunt:
    usage: /taunt <taunt type>
    permission: hide.default
    description: Taunt!
  ping:
    usage: /ping
    permission: hide.default
    description: Calculates your ping
  showhiders:
    usage: /showhiders
    permission: hide.admin
    description: Display hiders